### ISSUE TITLE
Undeclared dependency on SQL::Abstract::Limit

### ISSUE THREAD

**Issue by andk** [ywatase/JQuery-DataTables-Heavy#1]
As per sybject. Grep:

http://search.cpan.org/grep?release=JQuery-DataTables-Heavy-0.03;string=SQL::Abstract::Limit;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/45167772

HTH&&Thanks,
(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by ywatase** [comment]
Thanks for Report!
